name: Cleanup PR Preview

on:
  #  pull_request:
  #    types: [closed]
  #    paths:
  #      - 'apps/api/**'
  #      - 'apps/web/**'
  #      - 'packages/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    environment: Development
    concurrency:
      group: cleanup-pr-preview-${{ github.event.pull_request.number }}

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        with:
          version: '10.22.0'
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Remove PR preview environment
        run: pnpm sst remove --stage pr-${{ github.event.pull_request.number }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
