name: Deploy (Staging)

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'apps/web/**'
      - 'infra/**'
      - 'packages/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  test:
    uses: ./.github/workflows/test.yml

  run-migrations:
    uses: ./.github/workflows/run-migrations.yml
    with:
      environment: Staging
    secrets: inherit

  deploy:
    needs: [run-migrations, test]
    runs-on: ubuntu-latest
    environment: Staging
    concurrency:
      group: deploy-staging-${{ github.ref }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        with:
          version: '10.13.1'
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/cache@v4
        with:
          path: apps/web/.next/cache
          key: ${{ runner.os }}-nextjs-staging-${{ hashFiles('apps/web/**.[jt]s', 'apps/web/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-staging-

      - name: Deploy
        run: pnpm deploy:staging
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_WORKFLOW_WEBHOOK_URL: ${{ secrets.DISCORD_WORKFLOW_WEBHOOK_URL }}
          FEATURE_FLAG_RATE_LIMIT: ${{ vars.FEATURE_FLAG_RATE_LIMIT }}
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_HOST: ${{ secrets.LANGFUSE_HOST }}
          LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_REFRESH_TOKEN: ${{ secrets.LINKEDIN_REFRESH_TOKEN }}
          LINKEDIN_ORGANISATION_ID: ${{ secrets.LINKEDIN_ORGANISATION_ID }}
          LINKEDIN_USER_ID: ${{ secrets.LINKEDIN_USER_ID }}
          LTA_DATAMALL_API_KEY: ${{ secrets.LTA_DATAMALL_API_KEY }}
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_FEATURE_FLAG_UNRELEASED: ${{ vars.NEXT_PUBLIC_FEATURE_FLAG_UNRELEASED }}
          NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ vars.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_REVALIDATE_TOKEN: ${{ secrets.NEXT_PUBLIC_REVALIDATE_TOKEN }}
          QSTASH_CURRENT_SIGNING_KEY: ${{ secrets.QSTASH_CURRENT_SIGNING_KEY }}
          QSTASH_NEXT_SIGNING_KEY: ${{ secrets.QSTASH_NEXT_SIGNING_KEY }}
          QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
          QSTASH_URL: ${{ secrets.QSTASH_URL }}
          RESEND_AUDIENCE_ID: ${{ secrets.RESEND_AUDIENCE_ID }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          SG_CARS_TRENDS_API_TOKEN: ${{ secrets.SG_CARS_TRENDS_API_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          UPDATER_API_TOKEN: ${{ secrets.UPDATER_API_TOKEN }}
          UPSTASH_API_KEY: ${{ secrets.UPSTASH_API_KEY }}
          UPSTASH_EMAIL: ${{ secrets.UPSTASH_EMAIL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
